use std::{
  clone::Clone,
	fmt::{Debug, Display, Formatter, Result},
  marker::Copy,
};


/// contains CSSColorRGB, each struct is the representation of a CSS color keyword
pub static CSS_COLORS_RGB: &'static [CSSColorRGB] = &[
  CSSColorRGB {
    keyword: CSSKeyword::Aqua,
    r: 0,
    g: 255,
    b: 255,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Black,
    r: 0,
    g: 0,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Blue,
    r: 0,
    g: 0,
    b: 255,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Fuchsia,
    r: 255,
    g: 0,
    b: 255,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Gray,
    r: 128,
    g: 128,
    b: 128,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Green,
    r: 0,
    g: 128,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lime,
    r: 0,
    g: 255,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Maroon,
    r: 128,
    g: 0,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Navy,
    r: 0,
    g: 0,
    b: 128,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Olive,
    r: 128,
    g: 128,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Purple,
    r: 128,
    g: 0,
    b: 128,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Red,
    r: 255,
    g: 0,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Silver,
    r: 192,
    g: 192,
    b: 192,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Teal,
    r: 0,
    g: 128,
    b: 128,
  },
  CSSColorRGB {
    keyword: CSSKeyword::White,
    r: 255,
    g: 255,
    b: 255,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Yellow,
    r: 255,
    g: 255,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Aliceblue,
    r: 240,
    g: 248,
    b: 255,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Antiquewhite,
    r: 250,
    g: 235,
    b: 215,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Aquamarine,
    r: 127,
    g: 255,
    b: 212,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Azure,
    r: 240,
    g: 255,
    b: 255,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Beige,
    r: 245,
    g: 245,
    b: 220,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Bisque,
    r: 255,
    g: 228,
    b: 196,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Blanchedalmond,
    r: 255,
    g: 235,
    b: 205,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Blueviolet,
    r: 138,
    g: 43,
    b: 226,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Brown,
    r: 165,
    g: 42,
    b: 42,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Burlywood,
    r: 222,
    g: 184,
    b: 135,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Cadetblue,
    r: 95,
    g: 158,
    b: 160,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Chartreuse,
    r: 127,
    g: 255,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Chocolate,
    r: 210,
    g: 105,
    b: 30,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Coral,
    r: 255,
    g: 127,
    b: 80,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Cornflowerblue,
    r: 100,
    g: 149,
    b: 237,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Cornsilk,
    r: 255,
    g: 248,
    b: 220,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Crimson,
    r: 220,
    g: 20,
    b: 60,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Cyan,
    r: 0,
    g: 255,
    b: 255,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkblue,
    r: 0,
    g: 0,
    b: 139,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkcyan,
    r: 0,
    g: 139,
    b: 139,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkgoldenrod,
    r: 184,
    g: 134,
    b: 11,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkgray,
    r: 169,
    g: 169,
    b: 169,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkgreen,
    r: 0,
    g: 100,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkgrey,
    r: 169,
    g: 169,
    b: 169,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkkhaki,
    r: 189,
    g: 183,
    b: 107,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkmagenta,
    r: 139,
    g: 0,
    b: 139,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkolivegreen,
    r: 85,
    g: 107,
    b: 47,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkorange,
    r: 255,
    g: 140,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkorchid,
    r: 153,
    g: 50,
    b: 204,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Red,
    r: 139,
    g: 0,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darksalmon,
    r: 233,
    g: 150,
    b: 122,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkseagreen,
    r: 143,
    g: 188,
    b: 143,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkslateblue,
    r: 72,
    g: 61,
    b: 139,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkslategray,
    r: 47,
    g: 79,
    b: 79,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkslategrey,
    r: 47,
    g: 79,
    b: 79,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkturquoise,
    r: 0,
    g: 206,
    b: 209,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Darkviolet,
    r: 148,
    g: 0,
    b: 211,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Deeppink,
    r: 255,
    g: 20,
    b: 147,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Deepskyblue,
    r: 0,
    g: 191,
    b: 255,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Dimgray,
    r: 105,
    g: 105,
    b: 105,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Dimgrey,
    r: 105,
    g: 105,
    b: 105,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Dodgerblue,
    r: 30,
    g: 144,
    b: 255,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Firebrick,
    r: 178,
    g: 34,
    b: 34,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Floralwhite,
    r: 250,
    g: 250,
    b: 240,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Forestgreen,
    r: 34,
    g: 139,
    b: 34,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Gainsboro,
    r: 220,
    g: 220,
    b: 220,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Ghostwhite,
    r: 248,
    g: 248,
    b: 255,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Gold,
    r: 255,
    g: 215,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Goldenrod,
    r: 218,
    g: 165,
    b: 32,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Green,
    r: 0,
    g: 128,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Greenyellow,
    r: 173,
    g: 255,
    b: 47,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Grey,
    r: 128,
    g: 128,
    b: 128,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Honeydew,
    r: 240,
    g: 255,
    b: 240,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Hotpink,
    r: 255,
    g: 105,
    b: 180,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Indianred,
    r: 205,
    g: 92,
    b: 92,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Indigo,
    r: 75,
    g: 0,
    b: 130,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Ivory,
    r: 255,
    g: 255,
    b: 240,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Khaki,
    r: 240,
    g: 230,
    b: 140,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lavender,
    r: 230,
    g: 230,
    b: 250,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lavenderblush,
    r: 255,
    g: 240,
    b: 245,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lawngreen,
    r: 124,
    g: 252,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lemonchiffon,
    r: 255,
    g: 250,
    b: 205,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightblue,
    r: 173,
    g: 216,
    b: 230,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightcoral,
    r: 240,
    g: 128,
    b: 128,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightcyan,
    r: 224,
    g: 255,
    b: 255,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightgoldenrodyellow,
    r: 250,
    g: 250,
    b: 210,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightgray,
    r: 211,
    g: 211,
    b: 211,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightgreen,
    r: 144,
    g: 238,
    b: 144,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightgrey,
    r: 211,
    g: 211,
    b: 211,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightpink,
    r: 255,
    g: 182,
    b: 193,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightsalmon,
    r: 255,
    g: 160,
    b: 122,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightseagreen,
    r: 32,
    g: 178,
    b: 170,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightskyblue,
    r: 135,
    g: 206,
    b: 250,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightslategray,
    r: 119,
    g: 136,
    b: 153,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightslategrey,
    r: 119,
    g: 136,
    b: 153,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightsteelblue,
    r: 176,
    g: 196,
    b: 222,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Lightyellow,
    r: 255,
    g: 255,
    b: 224,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Limegreen,
    r: 50,
    g: 205,
    b: 50,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Linen,
    r: 250,
    g: 240,
    b: 230,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Magenta,
    r: 255,
    g: 0,
    b: 255,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Mediumaquamarine,
    r: 102,
    g: 205,
    b: 170,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Mediumblue,
    r: 0,
    g: 0,
    b: 205,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Mediumorchid,
    r: 186,
    g: 85,
    b: 211,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Mediumpurple,
    r: 147,
    g: 112,
    b: 219,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Mediumseagreen,
    r: 60,
    g: 179,
    b: 113,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Mediumslateblue,
    r: 123,
    g: 104,
    b: 238,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Mediumspringgreen,
    r: 0,
    g: 250,
    b: 154,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Mediumturquoise,
    r: 72,
    g: 209,
    b: 204,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Mediumvioletred,
    r: 199,
    g: 21,
    b: 133,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Midnightblue,
    r: 25,
    g: 25,
    b: 112,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Mintcream,
    r: 245,
    g: 255,
    b: 250,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Mistyrose,
    r: 255,
    g: 228,
    b: 225,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Moccasin,
    r: 255,
    g: 228,
    b: 181,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Navajowhite,
    r: 255,
    g: 222,
    b: 173,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Oldlace,
    r: 253,
    g: 245,
    b: 230,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Olivedrab,
    r: 107,
    g: 142,
    b: 35,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Orange,
    r: 255,
    g: 165,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Orangered,
    r: 255,
    g: 69,
    b: 0,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Orchid,
    r: 218,
    g: 112,
    b: 214,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Palegoldenrod,
    r: 238,
    g: 232,
    b: 170,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Palegreen,
    r: 152,
    g: 251,
    b: 152,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Paleturquoise,
    r: 175,
    g: 238,
    b: 238,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Palevioletred,
    r: 219,
    g: 112,
    b: 147,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Papayawhip,
    r: 255,
    g: 239,
    b: 213,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Peachpuff,
    r: 255,
    g: 218,
    b: 185,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Peru,
    r: 205,
    g: 133,
    b: 63,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Pink,
    r: 255,
    g: 192,
    b: 203,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Plum,
    r: 221,
    g: 160,
    b: 221,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Powderblue,
    r: 176,
    g: 224,
    b: 230,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Purple,
    r: 128,
    g: 0,
    b: 128,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Rosybrown,
    r: 188,
    g: 143,
    b: 143,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Royalblue,
    r: 65,
    g: 105,
    b: 225,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Saddlebrown,
    r: 139,
    g: 69,
    b: 19,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Salmon,
    r: 250,
    g: 128,
    b: 114,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Sandybrown,
    r: 244,
    g: 164,
    b: 96,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Seagreen,
    r: 46,
    g: 139,
    b: 87,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Seashell,
    r: 255,
    g: 245,
    b: 238,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Sienna,
    r: 160,
    g: 82,
    b: 45,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Skyblue,
    r: 135,
    g: 206,
    b: 235,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Slateblue,
    r: 106,
    g: 90,
    b: 205,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Slategray,
    r: 112,
    g: 128,
    b: 144,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Slategrey,
    r: 112,
    g: 128,
    b: 144,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Snow,
    r: 255,
    g: 250,
    b: 250,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Springgreen,
    r: 0,
    g: 255,
    b: 127,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Steelblue,
    r: 70,
    g: 130,
    b: 180,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Tan,
    r: 210,
    g: 180,
    b: 140,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Thistle,
    r: 216,
    g: 191,
    b: 216,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Tomato,
    r: 255,
    g: 99,
    b: 71,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Turquoise,
    r: 64,
    g: 224,
    b: 208,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Violet,
    r: 238,
    g: 130,
    b: 238,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Wheat,
    r: 245,
    g: 222,
    b: 179,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Whitesmoke,
    r: 245,
    g: 245,
    b: 245,
  },
  CSSColorRGB {
    keyword: CSSKeyword::Yellowgreen,
    r: 154,
    g: 205,
    b: 50,
  },
];


#[derive(Eq, PartialEq, PartialOrd)]
pub struct CSSColorRGB {
  pub keyword: CSSKeyword,
  pub r: u8,
  pub g: u8,
  pub b: u8,
}


impl Debug for CSSColorRGB {
  fn fmt(&self, f: &mut Formatter) -> Result {
    write!(
      f,

      "CSSColorRGB {{\
      \n  keyworkd: {}\
      \n  color: rgb({}, {}, {})\
      \n}}",

      self.keyword,
      self.r,
      self.g,
      self.b,
    )
  }
}


#[derive(Debug, Clone, Copy, Eq, Hash, PartialEq, PartialOrd)]
pub enum CSSKeyword {
  // css basic color keywords

  Aqua,
  Black,
  Blue,
  Fuchsia,
  Gray,
  Green,
  Lime,
  Maroon,
  Navy,
  Olive,
  Purple,
  Red,
  Silver,
  Teal,
  White,
  Yellow,

  // css extended color keywords

  Aliceblue,
  Antiquewhite,
  Aquamarine,
  Azure,
  Beige,
  Bisque,
  Blanchedalmond,
  Blueviolet,
  Brown,
  Burlywood,
  Cadetblue,
  Chartreuse,
  Chocolate,
  Coral,
  Cornflowerblue,
  Cornsilk,
  Crimson,
  Cyan,
  Darkblue,
  Darkcyan,
  Darkgoldenrod,
  Darkgray,
  Darkgreen,
  Darkgrey,
  Darkkhaki,
  Darkmagenta,
  Darkolivegreen,
  Darkorange,
  Darkorchid,
  Darkred,
  Darksalmon,
  Darkseagreen,
  Darkslateblue,
  Darkslategray,
  Darkslategrey,
  Darkturquoise,
  Darkviolet,
  Deeppink,
  Deepskyblue,
  Dimgray,
  Dimgrey,
  Dodgerblue,
  Firebrick,
  Floralwhite,
  Forestgreen,
  Gainsboro,
  Ghostwhite,
  Gold,
  Goldenrod,
  Greenyellow,
  Grey,
  Honeydew,
  Hotpink,
  Indianred,
  Indigo,
  Ivory,
  Khaki,
  Lavender,
  Lavenderblush,
  Lawngreen,
  Lemonchiffon,
  Lightblue,
  Lightcoral,
  Lightcyan,
  Lightgoldenrodyellow,
  Lightgray,
  Lightgreen,
  Lightgrey,
  Lightpink,
  Lightsalmon,
  Lightseagreen,
  Lightskyblue,
  Lightslategray,
  Lightslategrey,
  Lightsteelblue,
  Lightyellow,
  Limegreen,
  Linen,
  Magenta,
  Mediumaquamarine,
  Mediumblue,
  Mediumorchid,
  Mediumpurple,
  Mediumseagreen,
  Mediumslateblue,
  Mediumspringgreen,
  Mediumturquoise,
  Mediumvioletred,
  Midnightblue,
  Mintcream,
  Mistyrose,
  Moccasin,
  Navajowhite,
  Oldlace,
  Olivedrab,
  Orange,
  Orangered,
  Orchid,
  Palegoldenrod,
  Palegreen,
  Paleturquoise,
  Palevioletred,
  Papayawhip,
  Peachpuff,
  Peru,
  Pink,
  Plum,
  Powderblue,
  Rosybrown,
  Royalblue,
  Saddlebrown,
  Salmon,
  Sandybrown,
  Seagreen,
  Seashell,
  Sienna,
  Skyblue,
  Slateblue,
  Slategray,
  Slategrey,
  Snow,
  Springgreen,
  Steelblue,
  Tan,
  Thistle,
  Tomato,
  Turquoise,
  Violet,
  Wheat,
  Whitesmoke,
  Yellowgreen,
}


impl std::marker::Copy for CSSColorRGB {}


impl std::clone::Clone for CSSColorRGB {
  fn clone(&self) -> Self { todo!() }
}


impl Display for CSSKeyword {
	fn fmt(&self, f: &mut Formatter) -> Result {
		match &self {
      CSSKeyword::Aqua => write!(f, "aqua"),
      CSSKeyword::Black => write!(f, "black"),
      CSSKeyword::Blue => write!(f, "blue"),
      CSSKeyword::Fuchsia => write!(f, "fuchsia"),
      CSSKeyword::Gray => write!(f, "gray"),
      CSSKeyword::Green => write!(f, "green"),
      CSSKeyword::Lime => write!(f, "lime"),
      CSSKeyword::Maroon => write!(f, "maroon"),
      CSSKeyword::Navy => write!(f, "navy"),
      CSSKeyword::Olive => write!(f, "olive"),
      CSSKeyword::Purple => write!(f, "purple"),
      CSSKeyword::Red => write!(f, "red"),
      CSSKeyword::Silver => write!(f, "silver"),
      CSSKeyword::Teal => write!(f, "teal"),
      CSSKeyword::White => write!(f, "white"),
      CSSKeyword::Yellow => write!(f, "yellow"),
      CSSKeyword::Aliceblue => write!(f, "aliceblue"),
      CSSKeyword::Antiquewhite => write!(f, "antiquewhite"),
      CSSKeyword::Aquamarine => write!(f, "aquamarine"),
      CSSKeyword::Azure => write!(f, "azure"),
      CSSKeyword::Beige => write!(f, "beige"),
      CSSKeyword::Bisque => write!(f, "bisque"),
      CSSKeyword::Blanchedalmond => write!(f, "blanchedalmond"),
      CSSKeyword::Blueviolet => write!(f, "blueviolet"),
      CSSKeyword::Brown => write!(f, "brown"),
      CSSKeyword::Burlywood => write!(f, "burlywood"),
      CSSKeyword::Cadetblue => write!(f, "cadetblue"),
      CSSKeyword::Chartreuse => write!(f, "chartreuse"),
      CSSKeyword::Chocolate => write!(f, "chocolate"),
      CSSKeyword::Coral => write!(f, "coral"),
      CSSKeyword::Cornflowerblue => write!(f, "conrflowerblue"),
      CSSKeyword::Cornsilk => write!(f, "cornsilk"),
      CSSKeyword::Crimson => write!(f, "crimson"),
      CSSKeyword::Cyan => write!(f, "cyan"),
      CSSKeyword::Darkblue => write!(f, "darkblue"),
      CSSKeyword::Darkcyan => write!(f, "darkcyan"),
      CSSKeyword::Darkgoldenrod => write!(f, "darkgoldenrod"),
      CSSKeyword::Darkgray => write!(f, "darkgray"),
      CSSKeyword::Darkgreen => write!(f, "darkgreen"),
      CSSKeyword::Darkgrey => write!(f, "darkgrey"),
      CSSKeyword::Darkkhaki => write!(f, "darkkhaki"),
      CSSKeyword::Darkmagenta => write!(f, "darkmagenta"),
      CSSKeyword::Darkolivegreen => write!(f, "darkolivegreen"),
      CSSKeyword::Darkorange => write!(f, "darkorange"),
      CSSKeyword::Darkorchid => write!(f, "darkorchid"),
      CSSKeyword::Darkred => write!(f, "darkred"),
      CSSKeyword::Darksalmon => write!(f, "darksalmon"),
      CSSKeyword::Darkseagreen => write!(f, "darkseagreen"),
      CSSKeyword::Darkslateblue => write!(f, "darkslateblue"),
      CSSKeyword::Darkslategray => write!(f, "darkslategray"),
      CSSKeyword::Darkslategrey => write!(f, "darkslategrey"),
      CSSKeyword::Darkturquoise => write!(f, "darkturquoise"),
      CSSKeyword::Darkviolet => write!(f, "darkviolet"),
      CSSKeyword::Deeppink => write!(f, "deeppink"),
      CSSKeyword::Deepskyblue => write!(f, "deepskyblue"),
      CSSKeyword::Dimgray => write!(f, "dimgray"),
      CSSKeyword::Dimgrey => write!(f, "dimgray"),
      CSSKeyword::Dodgerblue => write!(f, "dodgerblue"),
      CSSKeyword::Firebrick => write!(f, "firebrick"),
      CSSKeyword::Floralwhite => write!(f, "floralwhite"),
      CSSKeyword::Forestgreen => write!(f, "forestgreen"),
      CSSKeyword::Gainsboro => write!(f, "gainsboro"),
      CSSKeyword::Ghostwhite => write!(f, "ghostwhite"),
      CSSKeyword::Gold => write!(f, "gold"),
      CSSKeyword::Goldenrod => write!(f, "goldenrod"),
      CSSKeyword::Greenyellow => write!(f, "greenyellow"),
      CSSKeyword::Grey => write!(f, "grey"),
      CSSKeyword::Honeydew => write!(f, "honeydew"),
      CSSKeyword::Hotpink => write!(f, "hotpink"),
      CSSKeyword::Indianred => write!(f, "indianred"),
      CSSKeyword::Indigo => write!(f, "indigo"),
      CSSKeyword::Ivory => write!(f, "ivory"),
      CSSKeyword::Khaki => write!(f, "khaki"),
      CSSKeyword::Lavender => write!(f, "lavender"),
      CSSKeyword::Lavenderblush => write!(f, "lavenderblush"),
      CSSKeyword::Lawngreen => write!(f, "lawngreen"),
      CSSKeyword::Lemonchiffon => write!(f, "lemonchiffon"),
      CSSKeyword::Lightblue => write!(f, "lightblue"),
      CSSKeyword::Lightcoral => write!(f, "lightcoral"),
      CSSKeyword::Lightcyan => write!(f, "lightcyan"),
      CSSKeyword::Lightgoldenrodyellow => write!(f, "lightgoldenrodyellow"),
      CSSKeyword::Lightgray => write!(f, "lightgray"),
      CSSKeyword::Lightgreen => write!(f, "lightgreen"),
      CSSKeyword::Lightgrey => write!(f, "lightgrey"),
      CSSKeyword::Lightpink => write!(f, "lightpink"),
      CSSKeyword::Lightsalmon => write!(f, "lightsalmon"),
      CSSKeyword::Lightseagreen => write!(f, "lightseagreen"),
      CSSKeyword::Lightskyblue => write!(f, "lightskyblue"),
      CSSKeyword::Lightslategray => write!(f, "lightslategray"),
      CSSKeyword::Lightslategrey => write!(f, "lightslategrey"),
      CSSKeyword::Lightsteelblue => write!(f, "lightsteelblue"),
      CSSKeyword::Lightyellow => write!(f, "lightyellow"),
      CSSKeyword::Limegreen => write!(f, "limegreen"),
      CSSKeyword::Linen => write!(f, "linen"),
      CSSKeyword::Magenta => write!(f, "magenta"),
      CSSKeyword::Mediumaquamarine => write!(f, "mediumaquamarine"),
      CSSKeyword::Mediumblue => write!(f, "mediumblue"),
      CSSKeyword::Mediumorchid => write!(f, "mediumorchid"),
      CSSKeyword::Mediumpurple => write!(f, "mediumpurple"),
      CSSKeyword::Mediumseagreen => write!(f, "mediumseagreen"),
      CSSKeyword::Mediumslateblue => write!(f, "mediumslateblue"),
      CSSKeyword::Mediumspringgreen => write!(f, "mediumspringgreen"),
      CSSKeyword::Mediumturquoise => write!(f, "mediumturquoise"),
      CSSKeyword::Mediumvioletred => write!(f, "mediumvioletred"),
      CSSKeyword::Midnightblue => write!(f, "midnightblue"),
      CSSKeyword::Mintcream => write!(f, "mintcream"),
      CSSKeyword::Mistyrose => write!(f, "mistyrose"),
      CSSKeyword::Moccasin => write!(f, "moccasin"),
      CSSKeyword::Navajowhite => write!(f, "navajowhite"),
      CSSKeyword::Oldlace => write!(f, "oldlace"),
      CSSKeyword::Olivedrab => write!(f, "olivedrab"),
      CSSKeyword::Orange => write!(f, "orange"),
      CSSKeyword::Orangered => write!(f, "orangered"),
      CSSKeyword::Orchid => write!(f, "orchid"),
      CSSKeyword::Palegoldenrod => write!(f, "palegoldenrod"),
      CSSKeyword::Palegreen => write!(f, "palegreen"),
      CSSKeyword::Paleturquoise => write!(f, "paleturquoise"),
      CSSKeyword::Palevioletred => write!(f, "palevioletred"),
      CSSKeyword::Papayawhip => write!(f, "papayawhip"),
      CSSKeyword::Peachpuff => write!(f, "peachpuff"),
      CSSKeyword::Peru => write!(f, "peru"),
      CSSKeyword::Pink => write!(f, "pink"),
      CSSKeyword::Plum => write!(f, "plum"),
      CSSKeyword::Powderblue => write!(f, "powderblue"),
      CSSKeyword::Rosybrown => write!(f, "rosybrown"),
      CSSKeyword::Royalblue => write!(f, "royalblue"),
      CSSKeyword::Saddlebrown => write!(f, "saddlebrown"),
      CSSKeyword::Salmon => write!(f, "salmon"),
      CSSKeyword::Sandybrown => write!(f, "sandybrown"),
      CSSKeyword::Seagreen => write!(f, "seagreen"),
      CSSKeyword::Seashell => write!(f, "seashell"),
      CSSKeyword::Sienna => write!(f, "sienna"),
      CSSKeyword::Skyblue => write!(f, "skyblue"),
      CSSKeyword::Slateblue => write!(f, "slateblue"),
      CSSKeyword::Slategray => write!(f, "slategray"),
      CSSKeyword::Slategrey => write!(f, "slategrey"),
      CSSKeyword::Snow => write!(f, "snow"),
      CSSKeyword::Springgreen => write!(f, "springgreen"),
      CSSKeyword::Steelblue => write!(f, "steelblue"),
      CSSKeyword::Tan => write!(f, "tan"),
      CSSKeyword::Thistle => write!(f, "thistle"),
      CSSKeyword::Tomato => write!(f, "tomato"),
      CSSKeyword::Turquoise => write!(f, "turquoise"),
      CSSKeyword::Violet => write!(f, "violet"),
      CSSKeyword::Wheat => write!(f, "wheat"),
      CSSKeyword::Whitesmoke => write!(f, "whitesmoke"),
      CSSKeyword::Yellowgreen => write!(f, "yellowgreen"),
		}
	}
}
